version: 2.1

workflows:
  version: 2
  build_and_test:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: golang:1.14.0-buster
    steps:
      - checkout
      - run:
          name: run tests
          command: ./circleci.sh
